### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by skills-up**

### CODE REVIEW

**Comment by benjamincrozat** [comment]
Closing, this is probably an error. 😅

**Comment by skills-up** [comment]
Apologies. I had to fork my own repo to be compatible with laravel 9+.

If you could just release the latest code with dependency update for contract repo, then I won't need to have my own repo.

**Comment by benjamincrozat** [comment]
Could you please do it? I'm unavailable for this task right now. That'd be great of you!

**Comment by skills-up** [comment]
It's creating a release that only you can do, or one of the contributors.

I don't have admin access to the repo, and this can't be done via a PR.

**Pull request closed without merging**
